import { adjacentItems } from './backpack-geometry.js'
import { consumableTargetCells } from './attack-range.js'
import { removeStatus } from './statuses.js'
import { manhattan } from '../core/geometry.js'

const CONSUMABLE_TYPES = new Set(['potion', 'armor', 'energy', 'buff', 'cleanse', 'teleport', 'throwable'])
const CLOCKWISE = [[0, -1], [1, -1], [1, 0], [1, 1], [0, 1], [-1, 1], [-1, 0], [-1, -1]]
export function isConsumable(item) { return CONSUMABLE_TYPES.has(item?.type) }

export class ConsumableRules {
  constructor(run) { this.run = run }
  chainPlan(item) {
    const { backpack } = this.run
    const ring = adjacentItems(backpack, item).find(source => source.id === 'r-chain-drink')
    if (!ring) return []
    const placement = backpack.placementOf(ring.uid)
    const surrounding = CLOCKWISE.map(([dx, dy]) => backpack.placementAt(placement.x + dx, placement.y + dy)?.item || null)
    const start = surrounding.findIndex(candidate => candidate?.uid === item.uid)
    const seen = new Set([item.uid]), plan = []
    for (let offset = 1; offset < 8; offset++) {
      const next = surrounding[(start + offset) % 8]
      if (isConsumable(next) && !seen.has(next.uid)) { plan.push(next); seen.add(next.uid) }
    }
    return plan
  }
  boosted(item, active) {
    return active && item.tier === 2 && adjacentItems(this.run.backpack, item).some(source => source.id === 'r-launcher')
  }
  targets(item) {
    if (item.type === 'throwable') return consumableTargetCells(this.run.currentRoom, this.run.player.pos, item)
    if (item.type !== 'teleport') return []
    const room = this.run.currentRoom, result = []
    for (let r = 0; r < room.height; r++) for (let c = 0; c < room.width; c++) {
      const pos = { c, r }, distance = manhattan(pos, this.run.player.pos)
      if (distance > 0 && distance <= 6 && room.isRevealed(pos) && room.isEmpty(pos)) result.push(pos)
    }
    return result
  }
  target(item, requested, active) {
    if (!['throwable', 'teleport'].includes(item.type)) return null
    const targets = this.targets(item)
    const match = targets.find(pos => pos.c === requested?.c && pos.r === requested?.r)
    if (match || active) return match || false
    targets.sort((a, b) => Number(this.run.currentRoom.entityAt(b)?.kind === 'enemy') - Number(this.run.currentRoom.entityAt(a)?.kind === 'enemy') ||
      manhattan(a, this.run.player.pos) - manhattan(b, this.run.player.pos) || a.r - b.r || a.c - b.c)
    return targets[0] || false
  }
  useSequence(item, position = null) {
    const plan = this.chainPlan(item)
    if (!this.consume(item, position, true)) return false
    // Snapshot the original neighborhood. Items generated by kills or the
    // furnace cannot enter this chain; every original item is used at most once.
    for (const next of plan) {
      if (this.run.gameOver) break
      if (!this.run.backpack.placementOf(next.uid)) continue
      if (!this.consume(next, position, false)) break
    }
    return true
  }
  consume(item, requested, active) {
    const { run } = this
    if (!isConsumable(item) || !run.backpack.placementOf(item.uid)) return false
    const target = this.target(item, requested, active)
    if (target === false) return active ? run._reject('\u8bf7\u9009\u62e9\u8303\u56f4\u5185\u7684\u6709\u6548\u76ee\u6807\u3002') : false
    const boosted = this.boosted(item, active)
    if (boosted && !run._spendEnergy(2)) return run._reject('\u6295\u63b7\u5668\u9700\u8981\u989d\u59162\u70b9\u4f53\u529b\u3002')
    run.backpack.removeByUid(item.uid)
    run.selectedInventoryIndex = null
    run.itemTargeting = false
    this.perform(item, target, boosted ? 1.5 : 1)
    run.itemRules.expansion.onConsumableUsed(item)
    run._log(`${active ? '\u4f7f\u7528' : '\u8fde\u996e\u73af\u514d\u8d39\u89e6\u53d1'} ${item.name}\u3002`)
    return true
  }
  perform(item, position, multiplier) {
    const { run } = this
    if (item.type === 'potion') run._healPlayer(item.heal + (run.hasTalent('survival-heal') ? 2 : 0) +
      (run.hasTalent('survival-last') && run.player.hp <= run.player.maxHp / 4 ? 5 : 0), { source: 'item:potion' })
    if (item.type === 'energy') run._recoverEnergy(item.energy)
    if (item.type === 'armor') run.itemRules.armor(item.armor)
    if (item.type === 'cleanse') {
      removeStatus(run.player, 'player-poison'); removeStatus(run.player, 'burning')
    }
    if (item.type === 'buff') {
      run.itemRules.buff('rage-wine', { flat: 4 })
      run._damagePlayer(2, { source: 'item:rage-wine', ignoreArmor: true })
    }
    if (item.type === 'teleport') {
      run.player.pos = { ...position }
      run._discoverNearbyExitDoors(); run._triggerAmbushes(position)
    }
    if (item.type === 'throwable') this.throw(item, position, multiplier)
  }
  throw(item, position, multiplier) {
    const { run } = this, room = run.currentRoom
    const enemies = [...room.entities.values()].filter(enemy => enemy.kind === 'enemy')
    const target = room.entityAt(position)
    const hit = (enemy, damage) => {
      if (run.gameOver || !room.entity(enemy.id)) return
      if (!room.isRevealed(enemy.pos)) run._revealEnemy(room, enemy, { cause: 'item:throw', triggerAlert: false })
      run._damageEnemy(enemy, Math.floor(damage * multiplier), { source: `item:${item.effect}` })
    }
    if (item.effect === 'poison') run.applyStatus(target, 'enemy-poison', { damage: Math.floor(item.poisonDamage * multiplier) }, { refresh: true })
    if (item.effect === 'explosion') for (const enemy of enemies.filter(enemy => Math.max(Math.abs(enemy.pos.c - position.c), Math.abs(enemy.pos.r - position.r)) <= 1)) hit(enemy, item.damage)
    if (item.effect === 'lightning') {
      const bounce = enemies.filter(enemy => enemy.id !== target.id && !enemy.downed)
        .sort((a, b) => manhattan(a.pos, position) - manhattan(b.pos, position) || a.id.localeCompare(b.id))[0]
      hit(target, item.damage)
      if (bounce) hit(bounce, item.bounceDamage)
    }
    if (item.effect === 'shield-bash') {
      const damage = run.player.armor
      run.player.armor -= Math.ceil(damage / 2)
      hit(target, damage)
    }
  }
}
